# Generated by Django 3.0.4 on 2021-08-11 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blockchain.Block')),
            ],
        ),
    ]
