# Generated by Django 3.2.6 on 2021-08-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_infofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='infofile',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='infofile',
            name='info',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
