# Generated by Django 3.2.6 on 2021-08-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_auto_20210813_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofile',
            name='info',
            field=models.BinaryField(null=True),
        ),
    ]
