# Generated by Django 3.2.6 on 2021-08-13 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_block_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Infofile',
        ),
    ]
