# Generated by Django 3.2.6 on 2021-08-13 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_delete_infofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.BinaryField(null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='created at')),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blockchain.block')),
            ],
        ),
    ]
